name: Tests on k3s

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v2
    - name: install k8s
      run: |
        mkdir -p ~/.kube
        if [[ -f ./kubeconfig ]];
        then
          echo "use existing kubeconfig"
          cp ./kubeconfig ~/.kube/config
        else
          echo "starting cluster"
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
          while [[ $(kubectl get nodes -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "Waiting for cluster nodes to be ready"; sleep 2; done
        fi
    - name: example tests
      env:
        REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
        REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
      run: |
        cd kyma-serverless
        bash ./kyma-init.sh
        export SERVER_ADDRESS=ghcr.io
        export REGISTRY_VALUES="dockerRegistry.username=$REGISTRY_USER,dockerRegistry.password=$REGISTRY_PASS,dockerRegistry.enableInternal=false,dockerRegistry.serverAddress=$SERVER_ADDRESS,dockerRegistry.registryAddress=$SERVER_ADDRESS/$REGISTRY_USER"       
        echo $REGISTRY_VALUES
        helm upgrade --wait -i serverless resources/serverless --set $REGISTRY_VALUES -n kyma-system
        kubectl wait --for condition=Ready=True pod -n kyma-system -l app=serverless
        kubectl apply -f assets/function.yaml
        bash assets/wait-for-function.sh
